import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Google Fonts'tan fontları yükler ve CSS değişkeni olarak tanımlar
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Sayfa başlığı ve açıklaması gibi SEO ayarları
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Font değişkenlerini ve Tailwind'in antialiased sınıfını gövdeye uygular
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children} {/* Sayfa içerikleri buraya basılır */}
      </body>
    </html>
  );
}